- name: Install & Configure Student App
  hosts: all
  become: yes
  roles:
    - nginx
    - tomcat
    - mariadb
  vars:
    - DBUSER: student
    - DBPASS: student1
    - DBNAME: studentapp
    - DBHOST: localhost
