# copy_file.yml
- name: copy files to destination
  hosts: deploy
  connection: ssh
  tasks:
    - name: copy schema file deployment Server 
      copy:
        src: files/configure_db_schema_nginx_app.sh
        dest: /home/goutham/configure_db_schema_nginx_app.sh
        owner: goutham
        group: goutham
        mode: 0744
      tags:
        - shell_script_copy
    - name: Execute Shell SCript
      shell:
         "./configure_db_schema_nginx_app.sh"
      args:
        chdir: "/home/goutham" 
      register: schema_status
      tags: schema
    - debug: msg="{{ schema_status }}"
